# FastAPI app, process entry point, and the Electron handshake.
#
# The worker is a child process, not a service. It binds loopback on an
# OS-assigned port, prints that port on stdout for its parent to read,
# and authenticates every request against a token its parent generated.
# Nothing else on the machine can reach it, which matters because it
# can move a producer's files.
import argparse
import json
import os
import sys
import threading

from fastapi import Depends, FastAPI, HTTPException, Query, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

import db
import jobs
import scanner
from platform_paths import normalize_path

VERSION = "0.1.0"

# Set from --token at startup, or UFORIYA_DEV_TOKEN when running under
# uvicorn directly in development.
TOKEN = os.environ.get("UFORIYA_DEV_TOKEN", "")

app = FastAPI(title="Uforiya Sample Organizer Worker", version=VERSION)


# ── Auth ─────────────────────────────────────────────────────────────────────

def require_token(request: Request) -> None:
    """
    Bearer token check on every route except /health.

    The token is generated by the Electron parent, passed on argv, and
    lives only in the two processes' memory. It is not a secret against
    the machine's owner — it stops other local processes driving a
    worker that can move files, which an open unauthenticated port
    would permit outright.
    """
    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer ") or auth[7:] != TOKEN:
        raise HTTPException(status_code=401, detail="Unauthorized")


def require_token_sse(token: str = Query(...)) -> None:
    """
    Token from a query parameter, for the SSE route only.

    Browser EventSource cannot set request headers — there is no
    mechanism for it in the API. The alternatives are hand-rolling SSE
    frame parsing over fetch + ReadableStream in the renderer, or this.

    The usual objections to tokens in URLs are server logs, referrer
    headers, and proxy caches. None exist here: the server is this
    process, there is no referrer on an EventSource request, and there
    is no proxy on loopback. Scoped to this one route so the header
    check stays the rule everywhere else.
    """
    if token != TOKEN:
        raise HTTPException(status_code=401, detail="Unauthorized")


# ── Schemas ──────────────────────────────────────────────────────────────────

class AddRootRequest(BaseModel):
    path: str


# ── Health ───────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    """Unauthenticated on purpose — it is how the parent confirms the
    worker came up, and it reveals nothing but a version string."""
    return {
        "status": "ok",
        "service": "uforiya-sample-organizer-worker",
        "version": VERSION,
    }


# ── Roots ────────────────────────────────────────────────────────────────────

@app.get("/library/roots", dependencies=[Depends(require_token)])
def get_roots():
    return {"roots": db.list_roots()}


@app.post("/library/roots", dependencies=[Depends(require_token)])
def post_root(body: AddRootRequest):
    """
    Registers a folder and starts a scan of every root.

    Validation is deliberately thin: the folder picker is a native
    Electron dialog, so the path came from the filesystem rather than
    a text field. The existence check is a backstop against a stale
    path, not an untrusted-input gate.
    """
    path = normalize_path(body.path)

    if not os.path.isdir(path):
        raise HTTPException(status_code=400, detail=f"Not a directory: {path}")

    root_id = db.add_root(path)
    job, started = jobs.registry.start_scan(_scan_all_roots)

    return {
        "root_id": root_id,
        "path": path,
        "job_id": job.id,
        "scan_started": started,
    }


@app.delete("/library/roots/{root_id}", dependencies=[Depends(require_token)])
def remove_root(root_id: int):
    """Forgets a root. Touches nothing on disk — this is 'stop tracking
    this folder', and the files stay exactly where they are."""
    if not db.delete_root(root_id):
        raise HTTPException(status_code=404, detail="Root not found")
    return {"deleted": True, "root_id": root_id}


# ── Scanning ─────────────────────────────────────────────────────────────────

def _scan_all_roots(job: jobs.Job) -> dict:
    """
    Job body: scans every registered root in sequence.

    Sequential rather than parallel because the bottleneck is the disk.
    Two roots on the same drive would contend; two roots on different
    drives would gain something, but not enough to justify interleaved
    progress reporting that a single progress bar cannot express.
    """
    summaries = []
    for root in db.list_roots():
        if job.is_cancelled():
            raise scanner.Cancelled()
        summaries.append(
            scanner.scan_root(
                root_id=root["id"],
                root_path=root["path"],
                emit=job.emit,
                is_cancelled=job.is_cancelled,
            )
        )

    return {
        "roots_scanned": len(summaries),
        "per_root": summaries,
        "totals": {
            "files_seen": sum(s["files_seen"] for s in summaries),
            "unchanged": sum(s["unchanged"] for s in summaries),
            "hashed": sum(s["hashed"] for s in summaries),
            "missing": sum(s["missing"] for s in summaries),
        },
    }


@app.post("/scan", dependencies=[Depends(require_token)])
def post_scan():
    """
    Rescans every root, incrementally.

    A scan already running returns that job rather than refusing, so
    the renderer subscribes to progress either way and never has to
    handle a conflict response.
    """
    job, started = jobs.registry.start_scan(_scan_all_roots)
    return {"job_id": job.id, "scan_started": started}


# ── Jobs ─────────────────────────────────────────────────────────────────────

@app.get("/jobs/{job_id}", dependencies=[Depends(require_token)])
def get_job(job_id: str):
    job = jobs.registry.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")
    return job.summary()


@app.get("/jobs/{job_id}/events", dependencies=[Depends(require_token_sse)])
def job_events(job_id: str):
    """
    SSE progress stream.

    Frames are written by hand rather than through a library: the
    format is four lines of text and the dependency is not worth
    carrying into a PyInstaller bundle.

    A None from the job generator is a keepalive, sent as a comment
    line. Comments are valid SSE that no client handler ever sees, so
    the connection stays warm without the renderer needing to filter
    anything out.
    """
    job = jobs.registry.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    def stream():
        for event in job.events():
            if event is None:
                yield ": keepalive\n\n"
            else:
                yield f"data: {json.dumps(event)}\n\n"

    return StreamingResponse(
        stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            # Harmless on loopback, but it costs nothing and prevents
            # any intermediary from buffering the stream into
            # uselessness.
            "X-Accel-Buffering": "no",
        },
    )


@app.post("/jobs/{job_id}/cancel", dependencies=[Depends(require_token)])
def cancel_job(job_id: str):
    """
    Requests cancellation. Cooperative, so this returns immediately
    while the scan stops within a file or two.

    Already-terminal jobs return their state rather than an error —
    cancelling something that just finished is not a failure from the
    user's point of view.
    """
    job = jobs.registry.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    if job.state in jobs.TERMINAL_STATES:
        return {"job_id": job_id, "state": job.state, "cancelled": False}

    job.cancel()
    return {"job_id": job_id, "state": job.state, "cancelled": True}


# ── Stats ────────────────────────────────────────────────────────────────────

@app.get("/library/stats", dependencies=[Depends(require_token)])
def library_stats():
    return {"counts": db.counts(), "roots": len(db.list_roots())}


# ── Shutdown ─────────────────────────────────────────────────────────────────

@app.post("/shutdown", dependencies=[Depends(require_token)])
def shutdown():
    """
    Graceful stop, called by Electron main on will-quit.

    The response is sent before the exit so the parent gets its
    acknowledgement — a timer thread does the actual killing a beat
    later. The parent still follows up with taskkill /T /F after a
    timeout, because a wedged worker must not be able to prevent the
    app from quitting.

    os._exit rather than sys.exit: sys.exit raises SystemExit in this
    thread only, which uvicorn catches and ignores. The DB is closed
    first so WAL files are checkpointed and the next launch does no
    recovery pass.
    """
    def _die():
        db.close()
        os._exit(0)

    threading.Timer(0.25, _die).start()
    return {"shutting_down": True}


# ── Entry point ──────────────────────────────────────────────────────────────

def main() -> None:
    """
    Binds, then announces.

    The READY line on stdout is the handshake: Electron main does not
    create its window until it parses this, because a renderer that
    loads before the backend exists fails its first request and shows
    an error on a working app.

    Port 0 lets the OS pick a free port, which avoids collisions with
    whatever else the producer is running. The actual port is only
    knowable after the socket binds, which is why it is read back from
    uvicorn's own server object rather than passed in.
    """
    global TOKEN

    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=0)
    parser.add_argument("--token", type=str, default="")
    parser.add_argument("--host", type=str, default="127.0.0.1")
    args = parser.parse_args()

    if args.token:
        TOKEN = args.token

    if not TOKEN:
        print("FATAL: no token supplied (--token or UFORIYA_DEV_TOKEN)", file=sys.stderr)
        sys.exit(1)

    import uvicorn

    config = uvicorn.Config(
        app,
        host=args.host,
        port=args.port,
        log_level="warning",
        access_log=False,
    )
    server = uvicorn.Server(config)

    # uvicorn binds the socket inside run(), so the assigned port is
    # not knowable until after startup. This thread waits for the
    # server to report started, reads the real port off the socket, and
    # prints the handshake line.
    def announce():
        import time
        while not server.started:
            time.sleep(0.01)
        port = server.servers[0].sockets[0].getsockname()[1]
        print(f"UFORIYA_READY {json.dumps({'port': port})}", flush=True)

    threading.Thread(target=announce, daemon=True).start()
    server.run()


if __name__ == "__main__":
    main()
